objc_library(
    name = "FLEX",
    module_name = "FLEX",
    srcs = glob(
        ["Classes/**/*"],
        exclude = [
            "Classes/Info.plist",
            "Classes/Utility/APPLE_LICENSE",
            "Classes/Network/OSCache/LICENSE.md",
            "Classes/Network/PonyDebugger/LICENSE",
            "Classes/GlobalStateExplorers/DatabaseBrowser/LICENSE",
            "Classes/GlobalStateExplorers/Keychain/SSKeychain_LICENSE",
            "Classes/GlobalStateExplorers/SystemLog/LLVM_LICENSE.TXT",
        ]
    ),
    hdrs = glob([
        "Classes/**/*.h"
    ]),
    includes = [
        "Classes",
        "Classes/Core",
        "Classes/Core/Controllers",
        "Classes/Core/Views",
        "Classes/Core/Views/Cells",
        "Classes/Core/Views/Carousel",
        "Classes/ObjectExplorers",
        "Classes/ObjectExplorers/Sections",
        "Classes/ObjectExplorers/Sections/Shortcuts",
        "Classes/Network",
        "Classes/Network/PonyDebugger",
        "Classes/Network/OSCache",
        "Classes/Toolbar",
        "Classes/Manager",
        "Classes/Manager/Private",
        "Classes/Editing",
        "Classes/Editing/ArgumentInputViews",
        "Classes/Headers",
        "Classes/ExplorerInterface",
        "Classes/ExplorerInterface/Tabs",
        "Classes/ExplorerInterface/Bookmarks",
        "Classes/GlobalStateExplorers",
        "Classes/GlobalStateExplorers/Globals",
        "Classes/GlobalStateExplorers/Keychain",
        "Classes/GlobalStateExplorers/FileBrowser",
        "Classes/GlobalStateExplorers/SystemLog",
        "Classes/GlobalStateExplorers/DatabaseBrowser",
        "Classes/GlobalStateExplorers/RuntimeBrowser",
        "Classes/GlobalStateExplorers/RuntimeBrowser/DataSources",
        "Classes/ViewHierarchy",
        "Classes/ViewHierarchy/SnapshotExplorer",
        "Classes/ViewHierarchy/SnapshotExplorer/Scene",
        "Classes/ViewHierarchy/TreeExplorer",
        "Classes/Utility",
        "Classes/Utility/Runtime",
        "Classes/Utility/Runtime/Objc",
        "Classes/Utility/Runtime/Objc/Reflection",
        "Classes/Utility/Categories",
        "Classes/Utility/Categories/Private",
        "Classes/Utility/Keyboard"
    ],
    copts = [
        "-Wno-deprecated-declarations",
        "-Wno-strict-prototypes",
        "-Wno-unsupported-availability-guard",
    ],
    deps = [],
    visibility = ["//visibility:public"],
)