filegroup(
    name = "SGNY",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    visibility = [
        "//visibility:public",
    ],
)

filegroup(
    name = "SGNYAssets",
    srcs = glob(["Images.xcassets/**"]),
    visibility = ["//visibility:public"],
)